meta:
  dns_root: (( param "please set meta dns_root" ))

name:          (( param "Please define the deployment name in the environment templates" ))
director_uuid: (( param "Please provide the UUID of your target BOSH director in the site/environment templates" ))

compilation:
  workers: 6
  network: named
  reuse_compilation_vms: true
  cloud_properties: (( param "please set compilation cloud properties" ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: false

resource_pools:
  - name: named
    network: named
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please set resource_pool cloud properties" ))
