jobs:
  - name: master
    templates:
    - { release: bind9, name: master  }
    instances: 1
    persistent_disk: 4096
    resource_pool: named
    networks: (( param "please set networks" ))
    properties:
      bind9:
        master:
          slaves: (( grab jobs.slave.networks.named.static_ips ))
          allow_transfer: (( grab networks.named.subnets[0].range ))
          zones:
            foo.bl: |+
              $TTL 1h
              $ORIGIN foo.bl.
              @ IN SOA foo.bl. hostmaster.foo.bl. (
                         2015082505  ; serial
                         15m         ; slaves should check back with us every 15min
                         20          ; slaves should retry (on failure) after 20sec
                         4h          ; slaves stop being authoritative after 4hr without updates
                         1h          ; other NSes should cache our results for 1h
                       )
                     IN NS ns1.foo.bl.
                     IN NS ns2.foo.bl.
                     IN A  10.0.0.42 ; bar
              ns1    IN A  10.0.0.11
              ns2    IN A  10.0.0.12
              bar    IN A  10.0.0.42
            10.in-addr.arpa: |+
              $TTL 1h
              $ORIGIN 10.in-addr.arpa.
              @ IN SOA foo.bl. hostmaster.foo.bl. (
                         2015082504  ; serial
                         15m         ; slaves should check back with us every 15min
                         20          ; slaves should retry (on failure) after 20sec
                         4h          ; slaves stop being authoritative after 4hr without updates
                         1h          ; other NSes should cache our results for 1h
                       )
                      IN NS  ns1.foo.bl.
                      IN NS  ns2.foo.bl.
              11.0.0  IN PTR ns1.foo.bl.
              12.0.0  IN PTR ns2.foo.bl.
              42.0.0  IN PTR bar.foo.bl.

  - name: slave
    templates:
    - { release: bind9, name: slave }
    instances: 2
    persistent_disk: 4096
    resource_pool: named
    networks: (( param "please set networks" ))
    properties:
      bind9:
        slave:
          master: (( grab jobs.master.networks.named.static_ips[0] ))
          allow_notify: (( grab networks.named.subnets[0].range ))
          zones:
            - foo.bl
            - 10.in-addr.arpa

networks: (( param "please set networks" ))
